### ISSUE TITLE
Says "Sinatra" instead of "Flask"

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-getting-remote-data-postman#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/pages/testing-apis-with-postman?module_item_id=480512

### Concern

You're probably already aware of this, but just in case you're not, we start this section out by writing `When developing web applications with Sinatra...` Instead of writing `Flask`.

**Comment by pgill97** [comment]
Fixed [578a886](https://github.com/learn-co-curriculum/python-p4-getting-remote-data-postman/commit/578a88620f88ef166de28f3edcbd3b2335051f6d).
